name: GHA

on:
  push:

jobs:

  job1:
    if: 1 == 0
    runs-on: ubuntu-latest
    steps:
      - run: echo OK

  job2:
    if: failure() == false
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo OK

  job3:
    if: cancelled() == false
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo OK

  job4:
    if: success() == false
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo OK

  job5:
    if: always()
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo OK

  job6:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo OK

  aggregate:
    if: always()
    needs:
      - job1
      - job2
      - job3
      - job4
      - job5
      - job6
    runs-on: ubuntu-latest
    steps:
      - run: echo job1 result=${{ needs.job1.result }}
      - run: echo job2 result=${{ needs.job2.result }}
      - run: echo job3 result=${{ needs.job3.result }}
      - run: echo job4 result=${{ needs.job4.result }}
      - run: echo job5 result=${{ needs.job5.result }}
      - run: echo job6 result=${{ needs.job6.result }}
