name: GHA pwsh

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm ci

      - name: reviewdog-eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: 'src/'
          level: warning

      - name: enable problem matcher
        run: |
          echo "::add-matcher::.github/eslint-stylish.problem-matcher.json"

      - name: eslint
        run: |
          npm run lint
